### ISSUE TITLE
PyGame WireFrame Renderer

### ISSUE THREAD

**Issue by AndreM0810** [mattbatwings/lampsim#1]
Hi! I was wondering if the WireFrame Renderer that you showcased on the video "I Made a 3D Renderer with just redstone!" around the 8:20 mark is publicly available?

**Comment by mattbatwings** [comment]
It is not

**Comment by mattbatwings** [comment]
I should mention though, my friend Matthias made a close recreation [here](https://gist.github.com/Matthias1590/44b1d13ebe13f22a3fb79e6066f115e2).
